all:
	# install pycocotools/mask locally
	# copy from https://github.com/pdollar/coco.git
	# /home/admin/miniconda3/envs/vilbert-mt/bin/python setup.py build_ext --inplace
	python setup.py build_ext --inplace
	rm -rf build

